version: '3.4'

services:
  product:
    container_name: e-commerce_product
    build: 
      context: ./product
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - e-commerce_network

  cart:
    container_name: e-commerce_cart
    build: 
      context: ./cart
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - e-commerce_network
  
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - e-commerce_network


networks:
  e-commerce_network:
    driver: bridge